name: Our Workflow
on: 
  push:
    # main에 대해서만 실행하도록 설정
    branches: [ main ]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # jdk 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        # 매개변수 설정
        with:
          java-version: '17'
          distribution: 'temurin'
          
        # 그래들 실행 권한 설정
      - name: 실행권한 설정
        run: chmod +x gradlew
        
        # 그래들 빌드
      - name: build
        run: ./gradlew bootJar
        # 이미지 생성
      - name: docker image build
        run: docker build -t span5189/hello-web:latest .
        # 도커 허브 로그인
      - name: docker hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        # 도커 허브 푸쉬
      - name: docker hub push
        run: docker push span5189/hello-web:latest
        
      